version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./data:/opt/keycloak/data/

volumes:
  data:
