version: "3.9"

services:
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init/:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
